### ISSUE TITLE
z-push sync email iOS more than one month

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#1324]
Z-push yncing for large mailboxes and sync more than 1 month doesnot work.

it only loads a few old mails and than stops with error.

```
24/08/2025 12:23:40 [3245188] [WARN] [mail@XXX] [5eqXXX4] Mobile loop detected! Messages sent to the mobile will be restricted to 2 items in order to identify the conflict
24/08/2025 12:23:41 [3245715] [ERROR] [mail@XXX] [5eqXXX4] LoopDetection->ProcessLoopDetectionPreviousConnectionFailed(): Command 'Sync' at 24/08/2025 12:18:29 with pid '3244285' terminated unexpectedly or is still running.
24/08/2025 12:23:41 [3245715] [ERROR] [mail@XXX] [5eqXXX4] Please check your logs for this PID and errors like PHP-Fatals or Apache segmentation faults and report your results to the Z-Push dev team.
```

As a workaround you could change to sync only 1 month in past, but that is not a real solution.

It worked like without errors until some update of group office this summer.

**Comment by mschering** [comment]
Hi,

Can you check your webserver logs to see what the error is that's causing the loop? Perhaps the memory_limit is exceeded or max_execution_time.

Best regards,
Merijn

**Comment by DUSAG0211** [comment]
I have the same error on 25.0.41. in apache error log
`[Fri Aug 29 23:06:01.323970 2025] [php:notice] [pid 9110:tid 9110] [client 10.194.82.193:57746] Error in /usr/share/groupoffice/go/modules/community/calendar/model/CalendarEvent.php at line 346: Typed property go\\modules\\community\\calendar\\model\\CalendarEvent::$calendarId must not be accessed before initialization
[Fri Aug 29 23:06:02.762783 2025] [php:notice] [pid 9113:tid 9113] [client 10.194.82.193:57750] Error in /usr/share/groupoffice/go/modules/community/calendar/model/CalendarEvent.php at line 346: Typed property go\\modules\\community\\calendar\\model\\CalendarEvent::$calendarId must not be accessed before initialization
[Fri Aug 29 23:06:03.933698 2025] [php:notice] [pid 9118:tid 9118] [client 10.194.82.193:57760] Error in /usr/share/groupoffice/go/modules/community/calendar/model/CalendarEvent.php at line 346: Typed property go\\modules\\community\\calendar\\model\\CalendarEvent::$calendarId must not be accessed before initialization
[Fri Aug 29 23:06:04.964208 2025] [php:notice] [pid 9111:tid 9111] [client 10.194.82.193:57762] Error in /usr/share/groupoffice/go/modules/community/calendar/model/CalendarEvent.php at line 346: Typed property go\\modules\\community\\calendar\\model\\CalendarEvent::$calendarId must not be accessed before initialization
`

i am trying to sync lots of entries from outlook desktop

**Comment by DUSAG0211** [comment]
My syncing issue is only with outlook 365 desktop. at some point it will stop while logs claim loop detection. resetting the loopdetect with zpushadmin did not help though. 
I have several IOS clients and also tried desktop thunderbird (with tbsync extension) and everything synced flawless.

One ios client randomly lost all calendards, despite activesync showing no errors and all entries were available in the groupoffice webview.

**Comment by mschering** [comment]
Please try with latest version . I believe this has already been fixed.

**Comment by remmedia** [comment]
Did not fix it for me.
Errorlog:

[Sun Aug 24 12:23:40.914410 2025] [proxy_fcgi:error] [pid 2892452:tid 2892477] [remote IP:PORT] AH01071: Got error 'PHP message: Error in /var/www/group-office/go/modules/community/calendar/model/CalendarEvent.php at line 346: Typed property  go\\modules\\community\\calendar\\model\\CalendarEvent::$calendarId must not be accessed before initialization'

**Comment by mschering** [comment]
Sorry to hear that. Would you be able to repeat the error with $config[‘debug’]=true; in the config.php file and then send the debug output with stack trace Here?

**Comment by remmedia** [comment]
guess that it is this

```
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:70] Error in /var/www/group-office/go/modules/community/calendar/model/CalendarEvent.php at line 352: Typed property go\modules\community\calendar\model\CalendarEvent::$calendarId must not be accessed before initialization
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #0 /var/www/group-office/go/modules/community/calendar/model/ICalendarHelper.php(358): go\modules\community\calendar\model\CalendarEvent->categoryIdsByName()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #1 /var/www/group-office/go/modules/community/calendar/model/Scheduler.php(239): go\modules\community\calendar\model\ICalendarHelper::parseVObject()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #2 /var/www/group-office/modules/z-push/backend/go/MailStore.php(1216): go\modules\community\calendar\model\Scheduler::handleIMIP()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #3 /var/www/group-office/modules/z-push/backend/go/MailStore.php(274): MailStore->processCalendarInvite()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #4 /var/www/group-office/go/modules/community/activesync/Z-Push/src/lib/default/diffbackend/exportchangesdiff.php(160): MailStore->GetMessage()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #5 /var/www/group-office/go/modules/community/activesync/Z-Push/src/lib/request/sync.php(1239): ExportChangesDiff->Synchronize()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #6 /var/www/group-office/go/modules/community/activesync/Z-Push/src/lib/request/sync.php(986): Sync->syncFolder()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #7 /var/www/group-office/go/modules/community/activesync/Z-Push/src/lib/request/requestprocessor.php(116): Sync->Handle()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #8 /var/www/group-office/go/modules/community/activesync/Z-Push/src/index.php(107): RequestProcessor::HandleRequest()
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #9 /var/www/group-office/modules/z-push/index.php(4): require('...')
[2025-09-01 17:58:56][ActiveSync][error][go\core\ErrorHandler:79] #10 {main}
```

**Comment by mschering** [comment]
Thanks, I've fixed the issue

**Comment by remmedia** [comment]
Still not loading emails. Stucks at the same position. Some old emails are loading and up from the same day in past (27.07.2012) they are still not loading. So there is no change to see with the latest update.

I‘ll Check log later to see if there ist something else or new

**Comment by mschering** [comment]
Sorry to hear that. Please post the current error of there are any.

**Comment by remmedia** [comment]
Now i got this error, have not seen before:
```
[2025-09-02 19:24:12][ActiveSync][log][go\core\auth\Authenticate:169] Authenticating mX@XXe.XXX
[2025-09-02 19:24:12][ActiveSync][log][go\core\ErrorHandler:115] ErrorHandler::exceptionHandler() called with TypeError
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:70] TypeError in /var/www/group-office/go/core/auth/TemporaryState.php at line 54: in_array(): Argument #2 ($haystack) must be of type array, string given
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #0 /var/www/group-office/go/core/auth/TemporaryState.php(54): in_array()
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #1 /var/www/group-office/go/core/auth/TemporaryState.php(19): go\core\auth\TemporaryState->setUserId()
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #2 /var/www/group-office/modules/z-push/backend/go/go.php(102): go\core\auth\TemporaryState->__construct()
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #3 /var/www/group-office/go/modules/community/activesync/Z-Push/src/lib/request/requestprocessor.php(68): BackendGO->Logon()
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #4 /var/www/group-office/go/modules/community/activesync/Z-Push/src/index.php(65): RequestProcessor::Authenticate()
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #5 /var/www/group-office/modules/z-push/index.php(4): require('...')
[2025-09-02 19:24:12][ActiveSync][error][go\core\ErrorHandler:79] #6 {main}
```

**Comment by remmedia** [comment]
Any idea? Can i do some more debugging to help?

**Comment by mschering** [comment]
You have set $config['debug_usernames'] to a string while it should be an array.

**Comment by remmedia** [comment]
Now it works again.

If i am right, this was a (comma separated) string in the past and even without debuging activated it breaks Sync, also with empty string value.

So it might be good in general zu have a Type Check/correction to default value and Hinz if nessessary to prevent such errors.
