### ISSUE TITLE
 6.4.65 - CronJob Today's events and tasks mailer failed

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#483]
EXCEPTION: PDOException: SQLSTATE[HY093]: Invalid parameter number in groupoffice-6.4.65-php-71/go/core/db/Statement.php:75
Stack trace:
#0 groupoffice-6.4.65-php-71/go/core/db/Statement.php(75): PDOStatement->execute(NULL)
#1 groupoffice-6.4.65-php-71/go/base/cron/CronJob.php(132): go\core\db\Statement->execute()
#2 groupoffice-6.4.65-php-71/modules/calendar/cron/EventAndTaskReportMailer.php(52): GO\Base\Cron\CronJob->getAllUsers()
#3 groupoffice-6.4.65-php-71/go/base/cron/CronJob.php(325): GO\Calendar\Cron\EventAndTaskReportMailer->run(Object(GO\Base\Cron\CronJob))
#4 groupoffice-6.4.65-php-71/cron.php(39): GO\Base\Cron\CronJob->run()
#5 {main}

**Comment by mschering** [comment]
By coincidence I just fixed that.

**Comment by IT-AND-GENERAL** [comment]
You are a star!! :-)

**Comment by IT-AND-GENERAL** [comment]
Hi,
This is still broken on 6.4.66
I guess the fix has not been released yet?


EXCEPTION: ErrorException: Can't get not existing property 'name' in 'GO\Calendar\Cron\EventAndTaskReportMailer' in groupoffice-6.4.66-php-71/go/base/Model.php:71
Stack trace:
#0 [internal function]: go\core\ErrorHandler::errorHandler(1024, 'Can't get not e...', 'g...', 71, Array)
#1 groupoffice-6.4.66-php-71/go/base/Model.php(71): trigger_error('Can't get not e...', 1024)
#2 groupoffice-6.4.66-php-71/modules/calendar/cron/EventAndTaskReportMailer.php(54): GO\Base\Model->__get('name')
#3 groupoffice-6.4.66-php-71/go/base/cron/CronJob.php(326): GO\Calendar\Cron\EventAndTaskReportMailer->run(Object(GO\Base\Cron\CronJob))
#4 groupoffice-6.4.66-php-71/cron.php(39): GO\Base\Cron\CronJob->run()
#5 {main}

**Comment by mschering** [comment]
Sorry, can you try to replace the file:

https://github.com/Intermesh/groupoffice/blob/1dffce553428773a07b18a5e3cacfbe03206276f/www/modules/calendar/cron/EventAndTaskReportMailer.php

**Comment by IT-AND-GENERAL** [comment]
I replaced the file and it looks it is completing with no errors but no email is sent

**Comment by IT-AND-GENERAL** [comment]
Upgraded to 6.4.67 and all seems ok now and we get emails.
